### ISSUE TITLE
Multiple Auth methods?

### ISSUE THREAD

**Issue by clintandrewhall** [ciaranj/connect-auth#1]
Should the additions to the session be partitioned by some kind of service identifier?  For instance, if I authenticate against both Twitter and Facebook, won't the user data in the session be overwritten?

**Comment by clintandrewhall** [comment]
Never mind, I'm an idiot... I need to read the code closer next time! ;-P

Apparently that's what the scope option is for... sigh... cheers!

**Comment by ciaranj** [comment]
err yes, it is ... but its not fully implemented yet :( .... but yes, thats exactly what its for :)

**Comment by phillro** [comment]
Is this still pending?

I am getting errors when I try to use scoping.

**Comment by phillro** [comment]
Am I reading this wrong or would implementing this just be a matter of modifying createAuthDetails ?
