### ISSUE TITLE
Add an explict LICENSE file

### ISSUE THREAD

**Issue by ozkatz** [ciaranj/connect-auth#125]
I saw in one of the closed issues that connect-auth is released under the MIT license.

I think i would be best to explicitly state this fact under the README, in addition to adding a LICENSE file. It's never good to be ambiguous about this sort of thing (see [this SO thread](http://stackoverflow.com/questions/5521080/can-i-use-the-code-in-a-github-project-which-does-not-have-a-license-specified)).

I'd be more than happy to supply a pull request ready with the needed changes.
Thanks again for a wonderful project :)

**Comment by ciaranj** [comment]
Hmm, odd thats usually one of the first things I add, a PR would be happily merged.
