### ISSUE TITLE
please publish new package -- connect-auth@0.1.3 fails to install on node@0.2.3/npm@0.2.3

### ISSUE THREAD

**Issue by jpld** [ciaranj/connect-auth#13]
commit 1e99df64d491208283fa appears to have fixed the install error but unfortunately connect-auth hasn't published an updated package for npm to fetch. installing from source works, but npm could really use an updated version for general consumption.

% npm install connect-auth
npm info it worked if it ends with ok
npm info using npm@0.2.3
npm WARN not supported on node@v0.2.3 connect-auth
npm WARN connect-auth supported engines: undefined
npm WARN not supported on node@v0.2.3 connect-auth
npm WARN connect-auth supported engines: undefined
npm WARN not supported on node@v0.2.3 connect-auth
npm WARN connect-auth supported engines: undefined
npm WARN not supported on node@v0.2.3 connect-auth
npm WARN connect-auth supported engines: undefined
npm WARN not supported on node@v0.2.3 connect-auth
npm WARN connect-auth supported engines: undefined
npm WARN not supported on node@v0.2.3 connect-auth
npm WARN connect-auth supported engines: undefined
npm WARN not supported on node@v0.2.3 connect-auth
npm WARN connect-auth supported engines: undefined
npm ERR! Error: connect-auth@0.1.3 not compatible with your version of node
npm ERR! Requires: node@
npm ERR! You have: node@v0.2.3
npm ERR!     at /usr/local/Cellar/npm/0.2.3/libexec/lib/install.js:173:32
npm ERR!     at c (/usr/local/Cellar/npm/0.2.3/libexec/lib/cache.js:47:12)
npm ERR!     at /usr/local/Cellar/npm/0.2.3/libexec/lib/cache.js:54:5
npm ERR!     at /usr/local/Cellar/npm/0.2.3/libexec/lib/utils/read-json.js:148:11
npm ERR!     at /usr/local/Cellar/npm/0.2.3/libexec/lib/utils/read-json.js:58:32
npm ERR!     at P (/usr/local/Cellar/npm/0.2.3/libexec/lib/utils/read-json.js:40:40)
npm ERR!     at cb (/usr/local/Cellar/npm/0.2.3/libexec/lib/utils/graceful-fs.js:28:9)
npm ERR!     at fs:84:13
npm ERR!     at node.js:768:9
npm ERR! npm install <tarball file>
npm ERR! npm install <tarball url>
npm ERR! npm install <folder>
npm ERR! npm install <pkg>
npm ERR! npm install <pkg>@<tag>
npm ERR! npm install <pkg>@<version>
npm ERR! npm install <pkg>@<version range>
npm ERR! 
npm ERR! Can specify one or more: npm install ./foo.tgz bar@stable /some/folder
npm ERR! Installs '.' if no argument supplied
npm ERR! try running: 'npm help install'
npm ERR! Report this _entire_ log at http://github.com/isaacs/npm/issues
npm ERR! or email it to npm-@googlegroups.com
npm not ok

**Comment by ciaranj** [comment]
Will do this shortly, I need to re-publish a few things :) (sorry)

**Comment by ciaranj** [comment]
Done (finally) .. sorry about that.

**Comment by jpld** [comment]
thank you!
