### ISSUE TITLE
Google?

### ISSUE THREAD

**Issue by drewlesueur** [ciaranj/connect-auth#14]
Will Google be added to the list anytime soon?
or has somebody got this working with Google authentication?

**Comment by ciaranj** [comment]
Would love to do this, haven't got the time at the mo, but I could give someone pointers if they wanted to help work on a strategy contribution?

**Comment by mhayashi** [comment]
I've wrote an authentication strategy for Google. I hope this is useful.  https://github.com/masahiroh/connect-auth/commit/1e5472b76ab76e894f382bfe40f9644be190454e

**Comment by drewlesueur** [comment]
Awesome, I will check it out.

**Comment by ciaranj** [comment]
Hiyah, thanks for this I've pulled the changes in, I think its a good stepping stone towards Google SSO support, but the real solution I think requires OpenID support (which there are at least 2 node modules being written to provide.)  When this comes along the authentication flow with google will be a lot tidier..with the OAuth approach we will keep getting prompted, which is a bit yukky atm :(

**Comment by mhayashi** [comment]
Indeed. I've added Google OAuth because I want to use Data API, but OpenID support is required for SSO. I don't know much about the OpenID's specification, but I'll give it a try:)

**Comment by dbrain** [comment]
Has anyone made any progress with this? There's what seems to be a fairly complete openid library [here](https://github.com/havard/node-openid).

**Comment by ciaranj** [comment]
I've not tried it myself, might be interesting now with G+ around.

**Comment by ciaranj** [comment]
There are now at least 2 different google SSO strategies provided, and a separate OpenId strategy :)
