### ISSUE TITLE
Plain Text Authentication for login form 

### ISSUE THREAD

**Issue by fxfred** [ciaranj/connect-auth#17]
Is it a good idea to add a simple plain text strategy? So all login method can use the same middleware. Or I have to use another auth module to login local users and mimic the interface of connect-auth.
SSL redirect option maybe needed for this strategy. :)

Thanks

**Comment by ciaranj** [comment]
I'm unsure quite what you mean, but there is a tutorial on the wiki that may help you: http://github.com/ciaranj/connect-auth/wiki/creating-a-form-based-strategy ?
