### ISSUE TITLE
openid

### ISSUE THREAD

**Issue by bentomas** [ciaranj/connect-auth#18]
Any plans to add openid support?  I'll help if I can, but I'm busy for the next few weeks!

**Comment by ciaranj** [comment]
I did start to look at this, but openid turns out to be a nightmare to implement, as soon as there is a node-openid library available (that works) I'll put this in place (I'd love to support the Google SSO properly) ( This is the library I'm watching : https://github.com/KushalP/node-openid )

**Comment by bentomas** [comment]
What about this: http://ox.no/software/node-openid ?

**Comment by ciaranj** [comment]
Implemented ;)
