### ISSUE TITLE
Problem with ndistro

### ISSUE THREAD

**Issue by dennisreimann** [ciaranj/connect-auth#19]
There is a problem when I'm using express and connect-auth and install both of them with ndistro. connect-auth overrides express' original link in the lib/node folder, so that express cannot be found anymore: http://img.ly/2rdH

**Comment by ciaranj** [comment]
Hmm, never used ndistro, any idea what the correct fix is ?

**Comment by dennisreimann** [comment]
I guess it would help to have a folder inside of lib/ which contains the files, like lib/connect-auth/ - connect is doing it that way, too: https://github.com/senchalabs/connect/tree/master/lib/

**Comment by ciaranj** [comment]
Removed old/pointless auth.s file, closed by 28ef2671a8f19ce1267420db802d1b904aae4d98 hopefully

**Comment by dennisreimann** [comment]
Okay, ndistro still links everything inside the lib/node folder, but now it works, because it doesn't overwrite the express link anymore.
