### ISSUE TITLE
pls rename lib/auth.js to lib/index.js

### ISSUE THREAD

**Issue by bryanwb** [ciaranj/connect-auth#2]
pls rename lib/auth.js to lib/index.js

I see that package.json specifies lib/auth.js as the main file but this breaks when using connect-auth without a package manager

**Comment by ciaranj** [comment]
Really, are you sure? ... I _think_ the examples run without a package manager, they use the form:

var auth= require('../lib/auth');    

Are they working by chance, what goes wrong for you ?

**Comment by bryanwb** [comment]
http://wiki.github.com/ciaranj/connect-auth/creating-a-form-based-strategy
uses the syntax
var auth= require('connect-auth');

to use connect-auth w/ my heroku instance I do the following

$ git clone git:....connect-auth.git connect-auth
$ cp -r connect-auth/lib ../my-heroku-project/vendor/lib/connect-auth
now at this point
http://github.com/bryanwb/undone/blob/master/server.js
require.paths.unshift("vendor/lib"); 
var connect = require('connect');
var express = require('express');
// this fails w/ auth.js but succeeds if I rename auth.js to index.js
var connect-auth = require('connect-auth');

**Comment by ciaranj** [comment]
require('connect-auth/auth') will work though ? ... I can see what you mean I'm just a little nervous changing it as it would break anyone who is currently doing connect-auth/auth :(

**Comment by na** [comment]
prehaps an index.js which exports auth.js or vice versa would satisfy both?

**Comment by ciaranj** [comment]
I'll introduce this change in 0.2.0  as I'm changing the HTTP strategies in a breaking way anyway, so I'll bundle this 'breaking' change in too :)

**Comment by ciaranj** [comment]
Done.
