### ISSUE TITLE
HTTP Digest auth fails if using connect.router

### ISSUE THREAD

**Issue by jharlap** [ciaranj/connect-auth#20]
connect.router modifies req.url, so when the digest auth strategy does `var href=req.url` and then uses href in constructing HA2 it is using a different url path than the client used, resulting auth always failing.

this is particularly the case if you do `server.use('/api', connect.router(routes));` and then attempt to use digest auth in the routes.

a solution would be to use the uri component of the authorization header, which reflects what the client used.

**Comment by ciaranj** [comment]
Ugghh I'll look into it :)

**Comment by ciaranj** [comment]
This should now be fixed, using req.originalUrl instead.
