### ISSUE TITLE
Allow 2-Legged OAuth to work as an OAuth provider

### ISSUE THREAD

**Issue by ramv** [ciaranj/connect-auth#21]
The _oauthstrategies.js is a bit too strict. 
requestToken method expects oauth_callback to be set and fails if it is not.
accessToken method expects oauth_verifier to be set and fails if it is not.
 2-Legged OAuth and 3-Legged OAuth work if this requirement is removed.

**Comment by ciaranj** [comment]
The OAuth strategy was a port of an existing 1.0A implementation.  I would like very much to support 2-legged OAuth, I've just not had the time to review the strategy to see the impact of running dual-mode (i.e. in 1.0A and the more accepting [verifier & callback free] 1.0 mode) .  If you can provide a patch I'll almost definitely pull it in as this has been on my todo list for ages.

**Comment by xentac** [comment]
Maybe I'm not understanding 2-legged oauth, but I thought you didn't need anything to do with request tokens to implement it.  I have used ramv's changes as inspiration for a second attempt at allowing 2-legged oauth in the oauth provider.

Hopefully this code is cleaner and easier to read and accept ;)

https://github.com/ciaranj/connect-auth/pull/76

**Comment by ciaranj** [comment]
Merged.

**Comment by ramv** [comment]
Thank Ciaran!

On Wed, Feb 29, 2012 at 2:31 PM, Ciaran Jessup <
reply@reply.github.com

> wrote:
> 
> Merged.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ciaranj/connect-auth/issues/21#issuecomment-4248277

## 

Best Regards,

Ram Viswanadha
