### ISSUE TITLE
bcrypt

### ISSUE THREAD

**Issue by DTrejo** [ciaranj/connect-auth#27]
It would be cool if there was a module like this for node, which makes using bcrypt really easy:

https://github.com/codahale/bcrypt-ruby

Developers\* who use express would be very happy if this were built in somehow.

Cheers,
David

*me

**Comment by ciaranj** [comment]
There are, for example this one: https://github.com/ncb000gt/node.bcrypt.js ... not sure this is anything to do with connect-auth though, although one might leverage it :)
