### ISSUE TITLE
Using connect-auth in combination with connect-mongodb to store sessions ...

### ISSUE THREAD

**Issue by tglines** [ciaranj/connect-auth#29]
I'm currently trying to get connect-auth to work together nicely with connect-mongodb to store the sessions.  I'm working with a dual facebook/custom login system.  Connect-auth works wonderfully for both when the sessions are stored in the default memory store.  

However when I switch over to connect-mongodb as the session store the facebook auth strategy works fine however my custom form based strategy fails.  Is there any known reason for this?

**Comment by ciaranj** [comment]
none that I'm aware of, what happens ? .. Is it possible that the custom form based strategy is using a null somewhere in the session ?

**Comment by tglines** [comment]
So I figured out what happens, or at least much more specifically where my problem is.  It seems that when using connect-mongodb ... the call to success inside the authenticate method of my custom form based strategy needs to have a field 'id' as the first parameter in order for req.isAuthenticated() to be true?

**Comment by tglines** [comment]
I tried your example that always authenticates and it works, however when I remove the id field as the first item it no longer works.

**Comment by ciaranj** [comment]
I'm a little puzzled, connect-auth doesn't rely on an id field anywhere that I'm aware?

**Comment by tglines** [comment]
I was too, sorry about all that ... I think I was trying to pass too much data through the sessions or some odd bug (i was passing a large json object).  I reduced the data I was passing and it now works like a charm.

**Comment by tglines** [comment]
closed, thank you for the help
