### ISSUE TITLE
success method doesn't set authenticated property to true

### ISSUE THREAD

**Issue by bryanwb** [ciaranj/connect-auth#3]
shouldn't the success method in authExecutionScope.js set the authenticated property to true?

AuthExecutionScope.prototype.success= function(user, callback) {
  this.executionResult.user= user;
  this.halt(callback);
};

How does one access the authenticated property?

**Comment by ciaranj** [comment]
When using the auth middleware, the request object gets augmented with an 'isAuthenticated(scope)' method.  'scope' is optional, this method should return true if the request is currently (or when using sessions, has previously been) authenticated. 

Is this what you mean ?
