### ISSUE TITLE
infinite redirect with 0.3.7 and github

### ISSUE THREAD

**Issue by aaronblohowiak** [ciaranj/connect-auth#31]
So, i get redirected to github which redirects back to my auth callback which redirects to the page the user wanted. yay.  but then this page redirects back to gh =(  i dont understand why that would happen.  the _same code_ runs on 0.2.5 / 0.2.6 without issue.

**Comment by aaronblohowiak** [comment]
I have created an [example application](https://github.com/aaronblohowiak/connect-auth-37-bug-example) which demonstrates this issue.

Are you planning on maintaining connect-auth?

**Comment by easternbloc** [comment]
It's broken in 0.3.6+

**Comment by tglines** [comment]
I think connect-auth is an amazing project, but seems that the last change was done November 28th.  It is and I think will be the go to authentication framework for node.js if people work on maintaining it and fixing issues.  I'll try and take a look @ it when I get a chance here but It'd be great to hear from some of the main contributors about its future.

**Comment by ciaranj** [comment]
Sorry for the delay, as it happens the break is over in node-oauth.  I've just commited a fix that resolves it in the 0.4.x compat fixes branch (of node-oauth.)  The github strategy works fine with this. (On 0.3.8) 

As soon as 0.4 is released I will be releasing relevant versions of all my libraries on npm :)

**Comment by easternbloc** [comment]
Figured that was the case when I saw you committing to the node-oauth branch earlier. 

Cheers dude. Looking forward to 0.4 and your updated libs ;)

**Comment by aaronblohowiak** [comment]
Cheers! Looking forward to it!

**Comment by tglines** [comment]
Thank you very much for responding to my post and updating things again, I was just concerned about the lack of activity.  I do have one question and posted the same to node-oath ... I'm still getting the repeating facebook redirects w/ the latest node-oath and connect-auth, any ideas?

**Comment by ciaranj** [comment]
I've just checked it here (connect-auth master HEAD not the latest tag, but that shouldn't make a difference) and it works for me (argh!)
