### ISSUE TITLE
error: socket hang up

### ISSUE THREAD

**Issue by ghost** [ciaranj/connect-auth#34]
Hi. First, thanks for the module. I upgrade to node v0.4.2 and when I run the example I get an error that says :

 node.js:116
      throw e; // process.nextTick error, or 'error' event on first tick
      ^
 Error: socket hang up
   at Client.<anonymous> (http.js:1502:26)
   at Client.emit (events.js:42:17)
   at Array.<anonymous> (net.js:800:12)
   at EvenEmitter._tickCallback (node.js:108:26)

It also happen in my app. Is there a solution?

**Comment by ciaranj** [comment]
did you upgrade to the latest vertsion of this module as well (and node-oauth if you're using oauth anywhere ? ) 

I've not had time to re-test the module against the latest version of connect, so there may be an issue there.

**Comment by ghost** [comment]
oh, it works doing upgrade : 'npm install oauth'.
thanks.

**Comment by atmos** [comment]
My apps eventually get into a state like this on express 2.0 and node 0.4.1.  Any idea where to start looking or what versions are worth cross checking to make sure I'm on the right ones?

**Comment by ciaranj** [comment]
Not had anyone mention this issue in a while...closing
