### ISSUE TITLE
No method 'authenticate'?

### ISSUE THREAD

**Issue by Qard** [ciaranj/connect-auth#37]
I can't seem to get connect-auth to work at all. It just spits out an error saying, "Object #<IncomingMessage> has no method 'authenticate'".

Using connect@1.2.1 and express@2.2.1 from npm. Is there any known issues with those versions?

Here's the code;

```
express = require('express');
auth = require('connect-auth');
fb = require('./fb_creds.js');
app = express.createServer();

app.configure(function(){
    app.use(app.router);
    app.use(auth([
        auth.Facebook({
            appId : fb.id
            , appSecret: fb.secret
            , scope : 'email'
            , callback: fb.callback
        })
    ]));
});

app.get('*', function(req,res) {
    req.authenticate(['facebook'], function(error, authenticated) {
        console.log('It isn\'t even getting this far... :(');
    });
});

app.listen(8080);
```

**Comment by ciaranj** [comment]
Strange, I'm not quite sure what the last combination  of versions I last tested was (things move extremely fast in the node world, as I'm sure you're aware) .. But it does look a little odd that your req variable is of type Incoming Message ???

**Comment by Qard** [comment]
It all still works normally though. I've been using req.params to grab route parts and that worked fine. What type should it be?

**Comment by ciaranj** [comment]
Just out of interest do the example apps work ?

**Comment by Qard** [comment]
Dunno. I installed connect-auth via npm also. I'm guessing the example apps were installed on my computer somewhere along with connect-auth?

**Comment by ciaranj** [comment]
ah yes, presumably ;)   This stuff _should_ just work (obviously) .. I'm a bit tied up at the mo to test for myself, I'll get on it asap :(

**Comment by Qard** [comment]
Tried running app.js in the examples folder and got this;
    node.js:134
              throw e; // process.nextTick error, or 'error' event on first tick
              ^
    TypeError: Object function createServer() {
      if ('object' == typeof arguments[0]) {
         return new HTTPSServer(arguments[0], Array.prototype.slice.call(arguments, 1));
      } else {
         return new HTTPServer(Array.prototype.slice.call(arguments));
      }
    } has no method 'cookieDecoder'
         at Object.<anonymous> (/usr/local/lib/node/.npm/connect-auth/0.2.2/package/examples/app.js:240:31)
         at Module._compile (module.js:404:26)
         at Object..js (module.js:410:10)
         at Module.load (module.js:336:31)
         at Function._load (module.js:297:12)
         at Array.<anonymous> (module.js:423:10)
         at EventEmitter._tickCallback (node.js:126:26)

**Comment by Qard** [comment]
Nevermind. I had the router before the auth middleware in configure()...duh. >.<

**Comment by sergi** [comment]
I am getting the exact same "Object # has no method 'authenticate'" error as @Qard. Using connect@1.3.0 and express@2.2.1 here.

**Comment by ciaranj** [comment]
Did you try the same 'fix' as Qard ?

**Comment by sergi** [comment]
My apologies, I did and now everything works. I guess the issue can be closed.

**Comment by ciaranj** [comment]
I'm kinda leaving it open as I get this question a _lot_ ;)

**Comment by Qard** [comment]
It's so easy to miss. >.>

**Comment by fadzril** [comment]
I'm still having this problem while trying to run example/app.js.

has no method 'cookieDecoder'
/connect-auth/examples/app.js:240:31

everything looks in order, cookieDecoder, session, bodyDecoder and router.
connect@1.6.1
express@2.4.4

**Comment by ciaranj** [comment]
You must be looking at some very old version there ? ..there's only 124 lines in app.js ?

**Comment by fadzril** [comment]
Ahhh~~ Really sorry about that! Seem like I'm still using old version. Thanks a lot ciaranj.

**Comment by ciaranj** [comment]
no worries :)

**Comment by billsaysthis** [comment]
I'm getting this error too and since I just installed yesterday I don't think it's an old version problem ;)

Here' my createServer block:

```
var app = express.createServer(
  express.bodyParser(),
  express.static(__dirname + "/public"),
  express.cookieParser(),
  auth_middleware(),
  express.session({ secret: 'xxx', store: new express.session.MemoryStore({ reapInterval: -1 }) }),
  express.router(routes)
);

Doesn't seem to matter if the auth_middleware call is before or after the session call.
```

**Comment by ciaranj** [comment]
Hey there, which error specifically as we seem to have a few different reports in this thread :) also it looks like you're not actually adding connect-auth in that list, but I'm not quite sure what auth_middleware is doing?

**Comment by mikebz** [comment]
I am getting the same issue.  Here is my app.js file:

```

/**
 * Module dependencies.
 */

var express = require('express')
  , routes = require('./routes')
  , auth= require('connect-auth')
  , url = require('url')
  , fs = require('fs')
  , events = require('./node_modules/connect-auth/lib/events')
  , OAuth= require('oauth').OAuth;


var app = module.exports = express.createServer();

// N.B. TO USE Any of the OAuth or RPX strategies you will need to provide
// a copy of the example_keys_file (named keys_file) 
try {
  var example_keys= require('./keys_file');
  for(var key in example_keys) {
    global[key]= example_keys[key];
  }
}
catch(e) {
  console.log('Unable to locate the keys_file.js file.');
}


// Configuration
app.configure(function(){
  app.use(express.methodOverride());
  app.set('views', __dirname + '/views');
  app.set('view engine', 'jade');
  app.use(express.bodyParser());
  app.use(app.router);
  app.use(express.static(__dirname + '/public'));
  app.use(auth({strategies:[ auth.Google2({appId : google2Id, appSecret: google2Secret, callback: google2CallbackAddress})
                     ], 
              trace: true, 
              logoutHandler: events.redirectOnLogout("/")}));
});

app.configure('development', function(){
  app.use(express.errorHandler({ dumpExceptions: true, showStack: true }));
});

app.configure('production', function(){
  app.use(express.errorHandler());
});

function authenticate (req, res, next) {
    req.authenticate(['Google2'], function (error, authenticated) {
      if( error ) {
          console.log("error happened in authentication");
          // Something has gone awry, behave as you wish.
          console.log( error );
          res.end();
      }
      else {
          console.log("authenticated...");
          if( authenticated === undefined ) {
            // The authentication strategy requires some more browser interaction, suggest you do nothing here!
          }
          else {
            // We've either failed to authenticate, or succeeded (req.isAuthenticated() will confirm, as will the value of the received argument)
            next();
          }
      }
    });
}

// Routes
app.get('/', authenticate, routes.index);

app.listen(3000);
console.log("Express server listening on port %d in %s mode", app.address().port, app.settings.env);
```

**Comment by Qard** [comment]
app.router strikes again!

Just remove app.use(app.router) or move the app.use(auth()) part above it.

**Comment by tj** [comment]
y u place auth under routes

**Comment by mikebz** [comment]
alright, that fixed it.  thanks (on to the next issue :)

**Comment by ciaranj** [comment]
@visionmedia :( because all of the Oauth/SSO style authentication methods _expect_ to call back on routes as part of the authentication handshake... you got any suggestions on how better to achieve that ? (I did strip out a load of router stuff when I ported over to connect 2!)

**Comment by tj** [comment]
middleware ideally are self-contained with just simple logic to match the pathnames etc, it might be handy to have a few utility function modules or something, but even with regexps you could do something similar easily:

``` js
app.use(function(req, res, next){
  var params;
  if (params = utils.match(req, 'GET /auth/:foo/:bar?')) {
   ...  
  }
...
})
```

I haven't looked at the oauth stuff so im not sure exactly what it needs but definitely best to not use app.get() etc in there for the ordering issues.

I've thought for a while about having each app.VERB() call create/.use() a middleware when called, there would be no app.router. It would fix situations like this, but it would complicate other things like configuration

**Comment by ciaranj** [comment]
Ok.  There (still) appears to be some confusion around the connect-auth middleware ;)   To be clear the connect-auth middleware does _NOT_ add any routes in by default, all the middleware does is add some utility methods to the request such as 'authenticate' or 'isAuthenticated' or 'logout'.

However! When you configure the authentication middleware you also provide it with 1 or more authentication strategies, now some of these (traditional ones such as Basic/Digest HTTP) operate purely on headers and don't need to 'add' routes into the application _but_ some (most!) of the strategies rely on SSO stuff like OAuth(1/2) or OpenID.  These strategies are required to 'expect' to be 'called back' to from another party [via the browser] so have to declare routes that the requests can be effectively handled on.  For most of these 'consumer' has some control over the url so could configure a standard pattern to be used (i.e. force all callbacks to come back on /auth/:foo etc.) but not all of them.  With this in mind I decided to let the consumer of the connect-auth 'framework' decide what callbacks they wanted to listen on... with the caveat that the auth middleware needs to come in 'early' in the connect stack ... it certainly' isn't ideal, but the alternative I could see would be you'd have to expose your routes outside of the authentication configuration which looked both messy and repetitive for the casual consumer of the framework ... does that make sense ?

**Comment by tj** [comment]
gotcha. hmmm. some of these auth things are so big they kinda dont really seem to fit too well as middleware, it's more just trying to cram routes/middleware/etc into middleware just to provide an API people are familiar with

**Comment by ciaranj** [comment]
Nope, and thats exactly why I separated them into the middleware part and the strategy part! .. its just that the middleware's not of much use without a decent strategy ;)  ... but entirely do-able, you could define your authentication method inline when you declare the auth middleware.. 

But yes the consistent API is what I was going for mostly (and as always this was for something _I_ needed, other people's mileage can and will vary ;) )
