### ISSUE TITLE
Connect-auth doesn't play well with Express

### ISSUE THREAD

**Issue by dominiek** [ciaranj/connect-auth#4]
When using Express, connect-auth only works by doing:

```
var app = express.createServer(
  ...
  auth( [
    auth.Twitter({consumerKey: TWITTER_CONSUMER_KEY, consumerSecret: TWITTER_CONSUMER_SECRET})        
  ])
);
```

But not when using the Express app.use thingies:

```
app.configure(function(){
  ...
  app.use(auth( [
    auth.Twitter({consumerKey: TWITTER_CONSUMER_KEY, consumerSecret: TWITTER_CONSUMER_SECRET})        
  ]))
});
```

**Comment by ciaranj** [comment]
Hmmm that sucks :( in Spain on hold ATM but will sort that asap!!!

**Comment by ciaranj** [comment]
Hmm, strange the following app: http://wiki.github.com/ciaranj/connect-auth/express-twitter-example  Works ok for me.

If you're seeing complaints along the lines of :

Error: Each layer must have a route and a handle function

Then I suspect you're suffering from the 'express' issue which is described in the following mailing list post(s): 

http://groups.google.co.uk/group/express-js/browse_thread/thread/61b59ad42f891d27?hl=en&pli=1

I just tested with HEAD of connect, and the npm version of express and all seems well.
