### ISSUE TITLE
Facebook example produce error: Can't set headers after they are sent

### ISSUE THREAD

**Issue by lexer** [ciaranj/connect-auth#42]
```
Error: Can't set headers after they are sent.
    at ServerResponse.<anonymous> (http.js:526:11)
    at ServerResponse.setHeader (/home/alexey/node_modules/connect/lib/patch.js:44:20)
    at next (/home/alexey/node_modules/connect/lib/http.js:168:13)
    at next (/home/alexey/node_modules/connect/lib/http.js:213:9)
    at /home/alexey/node_modules/connect/lib/middleware/session.js:296:9
    at /home/alexey/node_modules/connect/lib/middleware/session.js:311:9
    at Array.<anonymous> (/home/alexey/node_modules/connect/lib/middleware/session/memory.js:57:7)
    at EventEmitter._tickCallback (node.js:126:26
```

**Comment by mattaylor** [comment]
anyone?

**Comment by dz0ny** [comment]
Same here, this only happens when using cluster + nginx, when app (express) is started without cluster and with nginx this error doesn't occur. And it also happens with other providers (google,github..).

**Comment by frostbytten** [comment]
Actually, it happens with every OAuth2 provider (as of now). I am running pure node without any servers in front of it, with express and it gives the same error. I am working on tracking it down, but it has to do with two res.redirect calls. First call in the else clause at the bottom on facebook.js as well as the one on line 28. These are conflicting, trying to make a workaround now.

**Comment by andyzei** [comment]
i hit this too. connect-auth seems to be completely broken right now.

I just npm-installed the latest connect and connect-node. I hacked the example file down to just the facebook provider and it fails with this error.

**Comment by dz0ny** [comment]
Hi all,
maybe I have a solution for this see https://gist.github.com/1008882 (removed that.setupRoutes), replace with this auth strategy and manualy setup routes in your express/connect app.

```
app.get('/auth/facebook_callback', function(req, res){
    req.authenticate("facebook", function(error, authenticated) {
      res.redirect(req.session.facebook_redirect_url);
    });
});
```

**Comment by shamod** [comment]
dz0ny - i tried your strategy as shown above and it still fails with the same error.

has anyone resolved this issue?

**Comment by frostbytten** [comment]
I'm finishing up the patches that seem to work now. Working on the final failure clause. I should have something up within the hour.

**Comment by frostbytten** [comment]
Two options:
- Setup a counter to skip the first authentication === false on the "client" side (inside req.authenticated).
- Create a new option to have a FailedAuthUrl

Consensus?

**Comment by frostbytten** [comment]
Fixes available: frostbytten/connect-auth@eea4b62d2724f4ca58300a4360bcc3d0206b6b26

Please test.

**Comment by ciaranj** [comment]
Strange (Annoying) behaviour of github that I missed this conversation...err sorry!

**Comment by gerad** [comment]
+1 i'm getting this error with github oauth

**Comment by gerad** [comment]
traced the error that I'm seeing to its root cause, will open another issue and send a patch

**Comment by gerad** [comment]
this is the issue that I'm seeing: https://github.com/ciaranj/connect-auth/issues/54
