### ISSUE TITLE
dependencies?

### ISSUE THREAD

**Issue by gerad** [ciaranj/connect-auth#48]
connect-auth doesn't  declare any dependencies (ie oauth, connect) in its package.json

it seems to work for me, but I'm not sure how... it doesn't work for my buddy (same version of node 0.4.7 and npm 1.0.6)

**Comment by ciaranj** [comment]
Hmmm,  tricky one that.  I deliberately don't state dependencies on things like oauth as not everyone who uses connect-auth would neccessarily want to use the oauth authentication strategies, they may want to write their own or use the HTTP strategies for example.  I probably should list connect as a dependency but I guess that was a given as its pretty much fundamentally never going to be of any use with connect :) 

As to your buddy vs you did you use it through git and do a submodule update ?    To install oauth just do 'npm install oauth' if that is your (his/her) issue.  Any furrther detail on 'doesn't work' may hasten a resolution :)

**Comment by gerad** [comment]
Smart (about not listing dependencies). We made the dependencies explicit in
our package.json and everything ended up working out OK.

It might be worth listing connect as some people might choose to use
connect-auth with express (as we did).

Thannks for the help!
Gerad
On Jun 4, 2011 1:02 AM, "ciaranj" <
reply@reply.github.com>
wrote:

**Comment by ciaranj** [comment]
Hmm I think express depends on connect, so there is a transitive dependency (I actually only use connect-auth with express myself too ;) ) 

I'll close this for now :) Ty.

**Comment by c4milo** [comment]
I am having this issue , more info https://github.com/ciaranj/connect-auth/issues/50 . I haven't close it yet (#50) because I don't have permissions to reopen this issue
