### ISSUE TITLE
npm upgrade (currently a few months out of date)

### ISSUE THREAD

**Issue by RobKohr** [ciaranj/connect-auth#51]
I am unable to connect using facebook using the example in the wiki (it sends me through the facebook connect path but ends on "Facebook authentication failed :(").

I would log this as a bug, but after checking npm, it looks like it was last updated in march (almost 3 mths ago). Perhaps it is time to push an updated version out to npm (if things are mostly stable?) ?

Thanks,
Rob

**Comment by franklywatson** [comment]
I also had problems using the Facebook connect API.. I was going to spend some time digging this weekend and if i find out anything will see if i can feed that back into the mix... the unrelated facebook-js project does work however, based on some cursory tests

**Comment by RobKohr** [comment]
Thanks frankly, I will try it out and see if it works. FB connect alone is enough for right now, and I can just switch back to connect-auth later when it is working for fb.

**Comment by ciaranj** [comment]
Pushing out to npm now, Implemented in 0.3.0
