### ISSUE TITLE
connect-auth breaks the architecture of connect

### ISSUE THREAD

**Issue by timoxley** [ciaranj/connect-auth#53]
What do you think about these comments from: 
http://stackoverflow.com/questions/3498005/user-authentication-libraries-for-node-js/4975745#4975745

"… [connect-auth breaks] the very powerful and easy to read onion-ring architecture of connect. A no-go - my opinion :). …
It must use next() because thats the idea behind connect. Connect has a layer-architecture / form of code structure. And every layer has the power to stop the request execution by not calling next(). If we are talking about authentication: An authentication layer will check if the user has the correct permissions. If everything is fine the layer calls next(). If not this auth-layer generates an error and will not call next()

"

Strong words and I am just really interested to find out if you had any defense/reason as to why this is the case, or plans to refactor?

Thanks heaps :D

**Comment by ciaranj** [comment]
;) The beauty of open source is that different people have different opinions on what is correct. 

Authentication/Authorisation is _hard_.  I've put up a solution that worked ok for me for certain situations, certainly it needs much improvement (mainly in event-orientated areas such as 'new user' 'user logged out', 'user logged in', 'failed authentication url' etc. etc. ) 

The idea behind connect-auth was to provide a set of primitives to allow others to construct more complex architectures on-top-of!   So you could boot-strap your application using Basic or Digest HTTP authentication and with minimal change drop-in support for facebook, or twitter SSO, I've done all the messy stuff to support asynchronous database calls, messy url redirects etc. etc.  Sure you can start out doing something easy such as the examples given, but when it comes to writing something more 'real' you may find your code suddenly becoming architecturally complex (you'll end-up re-writing most of the core auth code again!) 

Strangely 'nivoc' repeatedly (on stackoverflow) asserts that connect idioms are broken by connect-auth, I would contend he's using it wrong ;) but I'm open to discussion :)

I've provided a set of primitives which are un-opinionated on how you use them, you're welcome to put them together in a fashion that you're comfortable with

To clarify the example provided at http://stackoverflow.com/questions/3498005/user-authentication-libraries-for-node-js/4975745#4975745  and at http://stackoverflow.com/questions/5099708/persistant-login-with-connect-auth/5108047#5108047 can be replicated (with increased clarity imho esp. as I would usually put the authentication strategy in a separate [and tested] file) with the following code:

```
var connect = require('connect');
var urlpaser = require('url');
var auth= require('connect-auth');

var urlStrategy= function() {
  return  {
      name : "URL"
    , authenticate : function(req, res, callback) { 
       if(   req.urlp.pathname == "/login"
          && req.urlp.query.name && req.urlp.query.name == "max" 
          && req.urlp.query.pwd && req.urlp.query.pwd == "herewego") {
          this.success( {name:req.urlp.query.name}, callback );
        }
        else {
          this.fail ( callback );
        }
     }
  }
};

var unauthed= function( res ) {
  res.writeHead(403);
  res.end('Sorry you are unauthorized.\n\nFor a login use: /login?name=max&pwd=herewego');
}
var authCheck = function (req, res, next) {
  url = req.urlp = urlpaser.parse(req.url, true);

  // ####
  // Logout
  if ( url.pathname == "/logout" ) {
    req.logout();
    unauthed( res );
  } 
  else { 
    // ####
    // Login/Authenticate
    req.authenticate( "URL", function( err, authenticated ) { 
      if( authenticated ) next();
      else unauthed( res );
    })
  }
}

var helloWorldContent = function (req, res, next) {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.end('authorized. Walk around :) or use /logout to leave\n\nYou are currently at '+req.urlp.pathname);
}

var server = connect.createServer(
      connect.logger({ format: ':method :url' }),
      connect.cookieParser(),
      connect.session({ secret: 'foobar' }),
      connect.bodyParser(),
      auth( urlStrategy() ),
      authCheck,
      helloWorldContent
);

server.listen(3000);
```

I hope this helps a little :)

**Comment by timoxley** [comment]
Wow, thanks for the great response, exactly what I was looking for. If you've got a stackoverflow account you should post that as a response on http://stackoverflow.com/questions/3498005/user-authentication-libraries-for-node-js/ and if you don't have an account, perhaps I'll quote you with a link back here. I don't like seeing libraries potentially misrepresented.

**Comment by timoxley** [comment]
Do you have any examples around of testing authentication as you described?

**Comment by ciaranj** [comment]
I do have a stackoverflow account, but I prefer not to get into "mine's better than your's style" discussions, all approaches usually have merit, and I apply a general 'meh, whatever' style approach to life :)  (hence MIT people are free to fork and fix as they see appropriate!)

re. testing, because strategies are usually just neatly encapsulated files, they can just be pulled in as normal to a testing framework of your choice (I tend to use vows, but I understand thats a bit old-hat nowadays).  The only real complexity with testing really is if you're doing a complex authentication that requires multiple potential redirects back to the client browser you need to stub out http clients, and the response objects   and provide dummy asserts for 'fail', 'success', 'redirect' etc. 

One major down-side of my library is the lack of tests :( It is an area that needs definite improvement, it is in fact the one thing stopping me from making more interesting changes, as I would prefer test coverage to new features, but finding the time has been difficult recently :( 

I normally do test things considerably better, e.g. http://github.com/ciaranj/node-oauth  honest :)
