### ISSUE TITLE
no data returned for facebook example

### ISSUE THREAD

**Issue by EugeneLiang** [ciaranj/connect-auth#59]
Hi, 
I've tried out your examples and Twitter works great! ( thank you for this )

However, Facebook example is not working,

I am receiving "undefined" for authenticated argument found at https://github.com/ciaranj/connect-auth/wiki/Express---Facebook-example-(with-additional-cunning-sign-in-page-redirect-logic)

I am using node.js 4.10 and Express.js 2.4.3

May I know if the example not working now? or am i missing something?

thanks and best regards.

**Comment by ciaranj** [comment]
ok.  yes that's to be 'expected' .. as of 0.3 the authenticated parameter comes through as a tri-state (true => Authenticated!, false => 'NOT authenticated, undefined => '... need to get the browser to redirect..or do something else' before continuing on ... an example where this is wired up for facebook can be found: https://github.com/ciaranj/connect-auth/wiki/Example-Basic-Middleware-Implementation-(Facebook)   

Please let me know how you get on :)  (The same behaviour should be being observed for Twitter too.. I'm surprised you didn't fall into it then!)

**Comment by EugeneLiang** [comment]
hey hello, thank you for your quick reply.

Twitter's still working ok, i've just tested it a while ago.

I'll try the example you have given me and get back to you as soon as possible.

Best.

**Comment by ciaranj** [comment]
I would expect Twitter + Facebook strategies to behave exactly the same, which is odd (the point of connect-auth is you shouldn't need to do different things for different strategies :) ) .. how did you get on ?

**Comment by EugeneLiang** [comment]
hello, 
i've tried the example (   https://github.com/ciaranj/connect-auth/wiki/Example-Basic-Middleware-Implementation-(Facebook)  ) but unfortunately it has the same error I am facing ( "undefined" for authenticated argument ).

Yes i find it weird too, but the twitter example is actually working.

**Comment by ciaranj** [comment]
Ok.  That example definitely works.  Is it at all possible that the URL you use to initially access your app differs from the one Facebook is redirecting back to?  If this is the case then you will see that sort of behaviour because that would involve two different (unrelated) sessions?
