### ISSUE TITLE
Why this library exposes bunch of globals?

### ISSUE THREAD

**Issue by Reinmar** [ciaranj/connect-auth#60]
https://github.com/ciaranj/connect-auth/blob/master/lib/auth.strategies/http/http.js#L10 -> Http object
https://github.com/ciaranj/connect-auth/blob/master/lib/auth.strategies/http/basic.js#L10 -> Basic object
https://github.com/ciaranj/connect-auth/blob/master/lib/auth.strategies/http/base.js#L5 -> Base object

etc, etc, etc. Requiring  this do awful mess in global object. Are these globals needed somewhere?

**Comment by ciaranj** [comment]
Um, what ? Thats the module exports .. I'm a little confused, thats pretty standard in node isn't it ? (they're not global in the 'window' sense of the word)

**Comment by Reinmar** [comment]
If You don't declare variable it is global even in node. It is accessible from any other module. Try adding 'use strict'; at the beginnings of all files. It will throw an error.

Of course I'm talking about variable names I listed above. No the module.exports, which is standard for node.

**Comment by ciaranj** [comment]
hmm, interesting.  I hadn't appreciated that (or used in for evil purposes) .. that code was re-factored to look like that by a contributor iirc and the pattern isn't used much elsewhere in the library.  As it bleeds it should be removed yes I concur.

**Comment by ciaranj** [comment]
I tell a lie they're everywhere...um sorry.

**Comment by Reinmar** [comment]
Happily it should be easy to fix that :)
For future I recommend You switching to strict mode. It fixes that stupid JS behaviours.

I wanted to be sure that I'm right here, so I've made little example:

m1.js:

``` javascript
require('./m2.js');
require('./m3.js');
console.log('m1', a);
```

m2.js:

``` javascript
a = 1;
```

m3.js:

``` javascript
console.log('m3', a);
```

And the result for node m1 is:

``` bash
$ node /www/tests/m1.js 
m3 1
m1 1
```

So this 'a' variable is accessible even in m3 module.
