### ISSUE TITLE
[Basic auth] Autologin after logout.

### ISSUE THREAD

**Issue by Reinmar** [ciaranj/connect-auth#61]
Hi,

I've got issue with basic strategy. After <code>req.logout()</code> calling <code>req.authenticate()</code> automatically logs mi in (without prompting for password). This happens for me in my project and also in example connect-auth provides. I have node 0.4.11 and latest version of connect-auth.

**Comment by ciaranj** [comment]
Yes, this is the way that basic authentication works (the browser remembers your credentials for a given realm as I understand it) ... a way around that is to produce a different authentication realm on each new authentication request. I thought I'd implemented that, perhaps I've not.

**Comment by Reinmar** [comment]
I thought that maybe this is normal behaviour, but I don't remember it from e.g. apache. But if You say so, ok. Is there any fast hack for this?

**Comment by ciaranj** [comment]
I'm looking into it now for you ..

**Comment by Reinmar** [comment]
Thank You :) I would help, but I'm unfamiliar with auth methods (as I proved above ;)

**Comment by ciaranj** [comment]
Yeah, so this _is_ expected behaviour, as I recalled... There are 2 approaches that spring to mind:

i) Send down a  HTTP/1.0 401 Unauthorized as part of the logout (this I imagine would suck as I don't know how you could redirect as part of that :( ) but it will force the login credentials to get blatted on the clientside.

ii) Dynamic realms... this is the 'cleanest' approach the current Http Auth strategies take a configurable realm parameter, but it is only settable at startup.  Really to do what you want that realm parameter needs to be tied to the current session/client ... the downside here is that would possibly introduce a dependency on session/cookies which isn't currently required by that strategy.

Thoughts?

**Comment by Reinmar** [comment]
I won't make it today, but I'll let You know how it works for me. Thanks.

**Comment by Reinmar** [comment]
I've read few things and now I know what are the issues of basic auth. It looks like it's not for my needs. And tweaking it with dynamic realms will do more mess than writing simple form auth :) So at this moment  I'm leaving connect-auth. Thanks for help.

**Comment by ciaranj** [comment]
;) sure ... just out of interest why could you not just write a specific strategy with connect-auth ?  (Most people actually use the Oauth strategies with Twitter etc. .. .)

**Comment by Reinmar** [comment]
Because I don't know how :) And for now it's easier for me to write ~30 lines of code than reading this https://github.com/ciaranj/connect-auth/wiki/creating-a-form-based-strategy 

In future, when I'll need auth via twitter or google, I'll switch back to Yours library and will write my own strategy :> But now I don't need oauth so writing from scratch is simpler.

**Comment by ciaranj** [comment]
;) Fair comment ... if you're interested (I am) when you're done could you send me what you did and I'll re-write it as a strategy,just so I can check that I haven't ruled out something that people are trying to do ?

**Comment by Reinmar** [comment]
I've partially already done that.

Here's my config section: https://github.com/Reinmar/planet/blob/master/config.js
There are two middlewares - auth (isAuthenticated, logout, etc) and secure_middleware (stupid name - I have to change it) that secures given path.

But strategy in fact is (or will be) also (or mostly :D) in action: https://github.com/Reinmar/planet/blob/master/actions/admin.js
But now there is hardcoded authentication. I will finish it and I think it will stay in actions, rather than in middleware. So I don't know if it fits to strategy in form how it's implemented in connect-auth.

When I'll finish this functionality I'll let You know.

**Comment by ciaranj** [comment]
Cheers.
