### ISSUE TITLE
not working example and make

### ISSUE THREAD

**Issue by avioli** [ciaranj/connect-auth#63]
Hi there,

I've got `node v0.4.10` and `npm 1.0.13` and I've got it installed thru npm - `npm install -g connect-auth`.
Got into `/usr/local/lib/node_modules/connect-auth`

When I try make I get:
`connect-auth (master) $ make
/bin/sh: ./support/expresso/bin/expresso: No such file or directory
make: *** [test] Error 127`

Turns out that npm doesn't install any support dir.
So I cloned it from git, but expresso is empty... as well as oauth.

Then I tried the example:
`connect-auth (master) $ node examples/app.js 
Caught exception: Error: EACCES, Permission denied
    at HTTPServer._doListen (net.js:1100:5)
    at net.js:1071:14
    at Object.lookup (dns.js:153:45)
    at HTTPServer.listen (net.js:1065:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/connect-auth/examples/app.js:122:8)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at Array.<anonymous> (module.js:421:10)`

Please, let me know what I can check, install do?
`npm ls` shows I've got all dependancies.

**Comment by ciaranj** [comment]
Hi there,

the default port the example runs at is port 80 ( some oauth providers only
redirect back to 80 ) so you will need to run it as sudo (or change the port
)

The makefile currently does nothing of use but was based on a template I
often use which assumes espresso is available for testing.  As there isn't
any real dependency on espresso I've not set it up in package.json,
confusing but not a problem :)

It looks like everything is fine fwiw!
- cj

On Friday, September 9, 2011, Ivo <
reply@reply.github.com>
wrote:

**Comment by avioli** [comment]
You are right, port 80 it is, and sudo did it.
Thanks
