### ISSUE TITLE
Facebook Documentation

### ISSUE THREAD

**Issue by ghalusa** [ciaranj/connect-auth#71]
"Express Facebook example (with additional cunning sign in page redirect logic)"

Needs ?method=facebook added to var fbCallbackAddress= "" comment.

Presently, it reads:
// this could point to your /signin page

Should read:
// this could point to your /signin?method=facebook page

In the signin route, it will always fail, because Facebook isn't returning the "method" URL variable.

**Comment by ashchan** [comment]
Very helpful, thanks!

**Comment by ghalusa** [comment]
Glad to help
