### ISSUE TITLE
Passing touch specific parameters in options to oAuth Dialog

### ISSUE THREAD

**Issue by baradas** [ciaranj/connect-auth#78]
Hi,
Is it currently possible to pass display parameters to the Facebook OAuth dialog using the current library?

**Comment by ciaranj** [comment]
I'm not sure, how does one 'normally' go about doing this ?

**Comment by baradas** [comment]
Just provide an additional option for display in options:

my.display =options.display || "page";
my._oAuth.getAuthorizeUrl({redirect_uri : my._redirectUri, scope: my.scope, display:my.display});

**Comment by ciaranj** [comment]
;) Thanks I meant on the facebook side! ... but yup that looks spot-on :)   Pull requests happily received!

**Comment by ciaranj** [comment]
The relevant pull request has been merged.
