### ISSUE TITLE
Previous request token checking in oauth strategy doesn't work

### ISSUE THREAD

**Issue by xentac** [ciaranj/connect-auth#83]
Right now the code looks like this:

```
self.provider.previousRequestToken(requestParameters['oauth_consumer_key'], function(err, result) {
```

But previousRequestToken in the example provider looks like this:

```
OAuthDataProvider.prototype.previousRequestToken = function(token, callback) {
  for(var key in this.oauth_previous_users_request_tokens) {
    if( this.oauth_previous_users_request_tokens[key] && this.oauth_previous_users_request_tokens[key].token == token ) {
      callback(new Error("Previously used token"));
      return;
    }
  }  
  callback(null, token);
}
```

It's checking the value of token, which definitely is not the oauth_consumer_key, it's the oauth_token.  The code on line 89 of _oauthservices.js needs to use oauth_token otherwise people could resubmit request tokens for access token generation.

**Comment by ciaranj** [comment]
Presumably this applies atop your other patches?   I'm so sorry I've still not merged this in yet, life seems crazy busy atm!

**Comment by xentac** [comment]
This change is actually entirely unrelated.  It's just something else I noticed in the code itself.

I think there's at least one more parallel request bug that's a little harder to address, but I'll see if I can come up with a way to fix it.

**Comment by ciaranj** [comment]
With the connect 2 release I'm going to do some merging tonight :)

**Comment by ciaranj** [comment]
merged.
