### ISSUE TITLE
After update to connect 2.0 error

### ISSUE THREAD

**Issue by tglines** [ciaranj/connect-auth#84]
I think you guys mentioned that you were looking at this tonight but I'm now getting this error.

```
TypeError: Object function createServer() {
  function app(req, res){ app.handle(req, res); }
  utils.merge(app, proto);
  utils.merge(app, EventEmitter.prototype);
  app.route = '/';
  app.stack = [].slice.apply(arguments);
  return app;
} has no method 'router'
    at Object.setupRoutes (/home/ubuntu/dev.shopaboo/node_modules/connect-auth/lib/auth.strategies/facebook.js:25:29)
```

**Comment by ciaranj** [comment]
Yup, looking at it now.

**Comment by tglines** [comment]
Awesome, thanks!

**Comment by ciaranj** [comment]
Done (not published yet, but in master) (unless you use openid)

**Comment by tglines** [comment]
Can you publish?

**Comment by ciaranj** [comment]
I was hoping to roll in some other changes first (and get openid working too)

**Comment by tglines** [comment]
Ahh ok, thanks for the update

**Comment by ciaranj** [comment]
Published now (0.5.0) Let me know how it works for you :)

**Comment by tglines** [comment]
Seems to work just fine so far, I'll keep you updated if that changes, thanks for the quick push!

**Comment by dennisreimann** [comment]
can confirm that upgrading to 0.5.0 fixed this error for me too, thanks a lot!
