### ISSUE TITLE
Sharing sessions across subdomains

### ISSUE THREAD

**Issue by tglines** [ciaranj/connect-auth#94]
Hey guys, this is more of an in depth question than an issue but figured it would get the most attention here.  (at least the lack of visibility in the docs is an issue)

I'm trying to share sessions across different subdomains of my domain.  For example if I have the main app running at www.myapp.com and I get a request to api.myapp.com I have the session in hand.  First off I share the backends with the same secret using connect-redis to store the sessions: (note ... code is in coffeescript)

```
RedisStore = require('connect-redis')(express)
sessionStore = new RedisStore({ db: 'sessions', host:config.redis_ip })

app.configure ->  app.set 'views', __dirname+'/views'  app.use express.bodyParser()  app.use express.methodOverride()
  app.use express.cookieParser()
  app.use express.session {    store: sessionStore, secret: 'myapp secret'  }
```

The best thing is that when I see a request come in on the api.myapp.com subdomain, it has the connect.sid cookie available.

However if I check req.isAuthenticated() ... it returns false indicating it doesn't match up the session correctly?

Does anyone have any ideas/suggestions?

**Comment by ciaranj** [comment]
Hmmm, have you tried enabling the trace logging, that will show you what session ids are being used by connect-auth :)

**Comment by tglines** [comment]
I enable that by doing something like this?

```
app.use auth {strategies:[
  auth.Facebook({appId:config.fbId, appSecret:config.fbSecret, scope:"email,read_friendlists,publish_actions",callback:config.fbCallbackAddress})
  ], trace:true}
```

**Comment by tglines** [comment]
I tried running the same exact code on two different servers on the same domain (both running off of www.myapp.com) and sending all requests for a certain url to one process (separate port proxyied/process and everything) and the auth worked fine.  I guess that removes some common denominators and this seems to be an issue specific to subdomains, not necessarily linking the session stuff up between processes.

**Comment by tglines** [comment]
I think this may be an issue with getting connect to issue the same cookie, because I've noticed that it's different.

**Comment by ciaranj** [comment]
hmm, I'm not sure, do you have some of the traces for example ?

**Comment by tglines** [comment]
Can't get trace to output anything ... I pass an object literal in with an array of strategies and the boolean trace as true.  Here's the code for the subdomain server I'm trying to get the recognize the main server's session:

```
express = require 'express'
app = express.createServer()
auth = require 'connect-auth'

config = require('./config').config

RedisStore = require('connect-redis')(express)
sessionStore = new RedisStore({ db: 'sessions', host:config.redis_ip })

app.configure ->
  app.set 'views', __dirname+'/views'
  app.use express.bodyParser()
  app.use express.methodOverride()
  app.use express.cookieParser()
  app.use express.session {
    store: sessionStore, secret: 'myapp secret'
  }
  auth_options=
    strategies: [ auth.Facebook({appId:config.fbId, appSecret:config.fbSecret, scope:"email,read_friendlists,publish_actions",callback:config.fbCallbackAddress}) ]
    trace: true

  app.use auth auth_options

  app.use express.logger {format:':date :remote-addr :method :status :url'}
  app.use express.static __dirname+'/public'
  app.use app.router

app.get '/', (req,res) ->
  console.log req.headers.cookie
  console.log req.session
  res.send 'test'

app.listen 8003
console.log 'server up at 8003'
```

**Comment by tglines** [comment]
It turns out that the default cookie generated by connect is just set on the domain, not set in a way the subdomains can read it.  Doing something like this will fix the issue nicely (sets the cookie on the base domain and allows it to be real from subdomains):

```
app.use express.session {
  store: sessionStore, secret: 'myapp secret', cookie:{ domain: '.myapp.com' }
}
```

**Comment by ciaranj** [comment]
I'm glad you got this working, but I'm a little concerned that tracing didn't work for you, what version of this library are you using ?

**Comment by daviddripps** [comment]
I'm using what I believe to be the correct cookie settings and I still can't get seem to share my session across subdomains.  Every time I log in to one subdomain the session persists until I make a request on the other subdomain at which point the cookie changes and my session is lost.  Here is my session setup on both subdomains:

``` javascript
//setup cookies and sessions
app.use(express.cookieParser());
app.use(express.session({
  key: app.config.session.key,
  secret: app.config.session.secret,
  store: new redisStore({
    host: app.config.db.hosts.master.host, 
    port: app.config.db.hosts.master.port, 
    pass: app.config.db.password
  }), 
  cookie: {
    path     : '/',
    domain   : '.mydomain.com',
    httpOnly : true,
    maxAge   : 1000*60*60*24*30*12    //one year(ish)
  }
}));
```

**Comment by ciaranj** [comment]
Hmmm, perhaps worth posting in the express mailing list as it sounds like the issue relates to express sessions rather than anything connect-auth specific?  (I moderate that list anyway ;) )

**Comment by daviddripps** [comment]
I'll do that, thanks.

**Comment by tglines** [comment]
Hmm ... @daviddripps my setup is very similar to yours and it's working fine.  One thing that helped me was logging the cookies to match them on the different subdomains.  This allowed me to clearly see that the cookie just wasn't getting there.  

Also have you cleared your cookies between the tests?  If not even though you now have the correct configuration it still may not work properly.

**Comment by tglines** [comment]
Also @ciaranj tracing is working fine I was just doing a few things wrong.

**Comment by ciaranj** [comment]
@tglines glad to hear it ;)

**Comment by daviddripps** [comment]
@tglines thanks for the suggestion, I think it helped a lot.

I logged the cookies and it's seeing the cookie in every case.  In the www subdomain however, it shows the correct value for the cookie on the first request, but changes it on all subsequent requests.

This leads me to believe that maybe there's a problem with the order of my static file handler or some other component in the app.configure outside the session handler.  is that a logical conclusion in your mind?
