### ISSUE TITLE
getting 'code' parameter from fb, but still not authorized

### ISSUE THREAD

**Issue by dolphin278** [ciaranj/connect-auth#95]
I've used 'Express Facebook example' to set up fb auth, and it works ok - i've seen FB privileges authorization page for my app, and then, i've got redirected to my '/somepage' (with huge 'code' url parameter - all in sync with fb docs), but in this page that i was redirected to, req.isAuthenticated() still returns false ;(
What can be the origin of the problem? I can provide any additional info, if needed.

**Comment by ciaranj** [comment]
Hmm, have you turned tracing on ?     If I had to guess I'd say you've been re-directed back to a different host (which has a different session identifier associated with it)
