### ISSUE TITLE
TypeError: Object #<Object> has no method 'fail'

### ISSUE THREAD

**Issue by djwglpuppy** [ciaranj/connect-auth#96]
<h3>The Issue</h3>

I was connecting to Twitter original as a root user... and then decided to go the scoped route (since I want their to be a facebook and twitter authentication possibly at the same time for the same user)

As soon as I connected as a scoped user I get this

```
DEBUG: /Users/david/Sites/SP/node_modules/connect-auth/lib/auth.strategies/twitter.js:60
                                    this.fail(callback);
                                         ^

DEBUG: TypeError: Object #<Object> has no method 'fail'
    at /Users/david/Sites/SP/node_modules/connect-auth/lib/auth.strategies/twitter.js:60:42
    at /Users/david/Sites/SP/node_modules/connect-auth/node_modules/oauth/lib/oauth.js:432:22
    at passBackControl (/Users/david/Sites/SP/node_modules/connect-auth/node_modules/oauth/lib/oauth.js:366:13)
    at IncomingMessage.<anonymous> (/Users/david/Sites/SP/node_modules/connect-auth/node_modules/oauth/lib/oauth.js:378:9)
    at IncomingMessage.emit (events.js:88:20)
    at HTTPParser.onMessageComplete (http.js:137:23)
    at CleartextStream.ondata (http.js:1150:24)
    at CleartextStream._push (tls.js:375:27)
    at SecurePair.cycle (tls.js:734:20)
    at EncryptedStream.write (tls.js:130:13)
```

I was able to fix the issue by Logging out using the `req.logout()` and reauthenticate... and now it works fine

<h3>Something I noticed</h3>

I looked at the `lib/auth.strategies/twitter.js` file and noticed this

``` javascript
                                function( error, oauth_token, oauth_token_secret, additionalParameters ) {
                                  if( error ) {
                                    self.trace( 'Error retrieving the OAuth Access Token: ' + error );
                                    request.getAuthDetails()['twitter_login_attempt_failed'] = true;
                                    this.fail(callback);
                                  }
```

I could not find anywhere the `fail()` function is created... 

The one issue for fail is one that needs to addressed I think, but also this brings up another situation about changing scopes after authneitcation... possibly a more elegant way of handling it?

**Comment by ciaranj** [comment]
Scopes have always been the poorly loved 3rd cousin, its quite likely they don't work in all (many?) situations, I'm sorry, we just never got around to implementing them fully :(

(for interests sake though, fail is defined: https://github.com/ciaranj/connect-auth/blob/master/lib/authExecutionScope.js  which is the 'scope' that code should be executing in) ... that 'this' should actually be 'self' . Clearly a bug!

**Comment by djwglpuppy** [comment]
@ciaranj --- Side note... once I got scopes set up appropriately... they are working great :smile:  Definitely a cousin worth kissing
