### ISSUE TITLE
OAuth data provider's tokenByConsumer() allows exactly one request token per consumer

### ISSUE THREAD

**Issue by evanp** [ciaranj/connect-auth#97]
The tokenByConsumer() interface of the OAuth data provider has this signature:

```
tokenByConsumer(consumer_key, callback)
```

...where the callback takes two arguments: an Error, and a token Object. The token object must be an object with a token and a token_secret attribute.

I _think_ this means that a consumer_key is used to retrieve a unique request token.

I also think this is a bad idea; it seems to mean that, while one user is authorizing an app, no other user can authorize that app. That seems wrong to me.

If this is correct and I'm just missing something, I could use some feedback. Otherwise, I'm going to submit a patch.

**Comment by ciaranj** [comment]
Hmm that code, is old, like I ported it from another library a _long_ time ago, so my memory is a bit hazy ;)

But I see what you mean,  it does look as though something is a-wry, I would think that it requires passing in the oauth_token (request token) as well as the consumer key ? (_oauthservices.js:105)

**Comment by evanp** [comment]
@ciaranj I think you're right.

Anyway, how about I submit a pull request with a backward-compatible way of doing it; something like:

if (provider.hasOwnProperty('tokenByConsumerAndToken')) {
     // use tokenByConsumerAndToken()
} else {
    // use tokenByConsumer()
}

I'm not sure how many other users of this strategy there are, but I always appreciate it when other folks minimize upgrade damage.

**Comment by ciaranj** [comment]
I couldn't agree more about minimizing upgrade damage, especially on framework-y stuff such as this, but it is important to balance that against making (already confusing) code more difficult to understand. (imho!) 

If we're not happy changing the method to always expect the oauth_token, how would you feel about making the oauth_token an optional argument (it will always be provided by oauth_services) and letting the provider's implementation determine if it should be one operation as a 1 consumer key + 1 user per app model or, multiple consumer key, users per app model ?  (we should change the provided example to utilise the latter model as I agree it is probably more the intention of this original code!)

**Comment by evanp** [comment]
That sounds OK, except I think the optional arg would have to be at the end, right? Something like:

```
tokenByConsumer(consumerKey, callback, optionalToken);
```

...which I think might be kind of clumsy.

**Comment by ciaranj** [comment]
That would be clumsy indeed :)   What I tend to do is 

```
function tokenByConsumer(consumerKey, optionalToken, callback) { 
   if( typeof optionalToken == "function" ) {
      callback= optionalToken;
      optionalToken= null;
   }
}
```

Which is _still_ clumsy, but only on the inside ;)

**Comment by evanp** [comment]
Riiiiight, but I was thinking that the person writing the Provider class is on the outside.

**Comment by ciaranj** [comment]
ah yes, there is that ;) (doh!) How about we just allow for the token to be passed as null ?
